Test "PIP2" interface example.

diff --git a/example/Makefile b/example/Makefile
--- a/example/Makefile
+++ b/example/Makefile
@@ -7,6 +7,25 @@ CC = gcc
 LDLIBS= -lpiplib32
 CFLAGS= -DLINEAR_VALUE_IS_INT -I $(PIPLIB_INC) -L $(PIPLIB_LIB)
 
+ROOT = ..
+
+PIPTEST = \
+	big \
+	brisebarre \
+	cg1 \
+	esced \
+	ex \
+	ex2 \
+	fimmel \
+	max \
+	negative \
+	small \
+	sor1d \
+	square \
+	sven
+
+BITS = 64
+
 example: example.c 
 	@echo "             /*-----------------------------------------------*"
 	@echo "              *                Making example                 *"
@@ -21,3 +40,27 @@ clean:
 	@echo "              *               Cleaning example                *"
 	@echo "              *-----------------------------------------------*/"
 	-rm -f example example.exe core
+
+test:
+	failedtest=0; \
+	for x in $(PIPTEST) ; do \
+		echo "Verify file $$x" ; \
+		$(ROOT)/obj$(BITS)_$(TARGET)/example$(BITS)$(EXEC_SUFFIX) < $$x.pip > xyz ;\
+		diff -w xyz $$x.ll ; \
+		result=$$?; \
+		if [ "$$result" -eq "1" ]; then \
+			echo "Error: $$x is not the same"; \
+			failedtest=`expr $$failedtest + 1`; \
+		else \
+			echo "$$x passed"; \
+	        fi; \
+	done ; \
+	rm xyz ; \
+	if [ $$failedtest != 0 ]; then \
+		echo "$$failedtest tests failed"; \
+	else \
+	        echo "PIP works correctly :-)"; \
+        fi
+
+# Include the shared compilation rules
+include $(ROOT)/Makefile
